/**
 * Curated listings — each image URL matches property type/category.
 */
const { TITLE_IMAGE_MAP, catalogImage } = require("./provenImages.js");
const img = catalogImage;

const LISTING_CATALOG = [
  {
    title: "Oceanfront Beach Cottage",
    description: "Steps from the sand with a private patio, outdoor shower, and sunrise views.\nPerfect for couples seeking a calm coastal escape.",
    category: "Amazing pools",
    propertyType: "Entire place",
    price: 1850,
    location: "Malibu",
    country: "United States",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Free parking", "Pool"],
    image: { url: img("photo-1499793983690-e29da59ef1c2"), filename: "beach" },
    coordinates: { lat: 34.0259, lng: -118.7798 },
  },
  {
    title: "Tropical Beachfront Bungalow",
    description: "Private pool, palm trees, and direct beach access in southern Bali.",
    category: "Amazing pools",
    propertyType: "Entire place",
    price: 2200,
    location: "Bali",
    country: "Indonesia",
    maxGuests: 6,
    amenities: ["WiFi", "Pool", "Kitchen", "Breakfast"],
    image: { url: img("photo-1602343168117-bb8ffe3e2e9f"), filename: "bali-beach" },
    coordinates: { lat: -8.4095, lng: 115.1889 },
  },
  {
    title: "Luxury Overwater Villa",
    description: "Glass-floor panels, infinity pool, and butler service over crystal lagoons.",
    category: "Amazing pools",
    propertyType: "Entire place",
    price: 8500,
    location: "Maldives",
    country: "Maldives",
    maxGuests: 4,
    amenities: ["WiFi", "Pool", "Breakfast", "Air conditioning"],
    image: { url: img("photo-1439066615861-d1af74d74000"), filename: "maldives" },
    coordinates: { lat: 3.2028, lng: 73.2207 },
  },
  {
    title: "Cliffside Infinity Pool Villa",
    description: "Santorini-caliber views with heated infinity pool and wine cellar.",
    category: "Amazing pools",
    propertyType: "Entire place",
    price: 5200,
    location: "Mykonos",
    country: "Greece",
    maxGuests: 8,
    amenities: ["WiFi", "Pool", "Kitchen", "Hot tub"],
    image: { url: img("photo-1602343168117-bb8ffe3e2e9f"), filename: "villa-pool" },
    coordinates: { lat: 37.4467, lng: 25.3289 },
  },
  {
    title: "Alpine Ski Chalet",
    description: "Ski-in/ski-out access, stone fireplace, and panoramic mountain decks.",
    category: "Mountains",
    propertyType: "Entire place",
    price: 3400,
    location: "Aspen",
    country: "United States",
    maxGuests: 8,
    amenities: ["WiFi", "Kitchen", "Free parking", "Washer"],
    image: { url: img("photo-1502784444187-359ac186c5bb"), filename: "chalet" },
    coordinates: { lat: 39.1911, lng: -106.8175 },
  },
  {
    title: "Cozy Mountain Cabin",
    description: "Wood-burning stove, forest trails, and stargazing from the hot tub.",
    category: "Mountains",
    propertyType: "Entire place",
    price: 1400,
    location: "Banff",
    country: "Canada",
    maxGuests: 5,
    amenities: ["WiFi", "Kitchen", "Hot tub", "Free parking"],
    image: { url: img("photo-1449158743715-0a0908a71f9a"), filename: "cabin" },
    coordinates: { lat: 51.1784, lng: -115.5708 },
  },
  {
    title: "Himalayan Retreat Lodge",
    description: "Tea-house breakfasts and snow-capped peaks from every window.",
    category: "Mountains",
    propertyType: "Unique stay",
    price: 980,
    location: "Manali",
    country: "India",
    maxGuests: 4,
    amenities: ["WiFi", "Breakfast", "Kitchen"],
    image: { url: img("photo-1464822759023-fed622ff2c3b"), filename: "himalaya" },
    coordinates: { lat: 32.2432, lng: 77.1892 },
  },
  {
    title: "Modern Downtown Loft",
    description: "Floor-to-ceiling windows, skyline views, and walkable nightlife.",
    category: "Iconic Cities",
    propertyType: "Entire place",
    price: 2100,
    location: "New York City",
    country: "United States",
    maxGuests: 3,
    amenities: ["WiFi", "Workspace", "Air conditioning", "TV"],
    image: { url: img("photo-1502672260266-1c1ef2d93688"), filename: "loft" },
    coordinates: { lat: 40.7128, lng: -74.006 },
  },
  {
    title: "Parisian Haussmann Apartment",
    description: "Mouldings, marble fireplace, and Eiffel glimpses from the balcony.",
    category: "Iconic Cities",
    propertyType: "Entire place",
    price: 2800,
    location: "Paris",
    country: "France",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Washer", "Dryer"],
    image: { url: img("photo-1505693416388-ac5ce068fe85"), filename: "paris-apt" },
    coordinates: { lat: 48.8566, lng: 2.3522 },
  },
  {
    title: "Tokyo Designer Apartment",
    description: "Minimal interiors, smart home features, and metro at your door.",
    category: "Iconic Cities",
    propertyType: "Entire place",
    price: 1950,
    location: "Tokyo",
    country: "Japan",
    maxGuests: 2,
    amenities: ["WiFi", "Workspace", "Air conditioning", "TV"],
    image: { url: img("photo-1522708323590-d24dbb6b0267"), filename: "tokyo" },
    coordinates: { lat: 35.6895, lng: 139.6917 },
  },
  {
    title: "Barcelona Gothic Quarter Flat",
    description: "Terrace, local markets, and Gaudí architecture within walking distance.",
    category: "Iconic Cities",
    propertyType: "Entire place",
    price: 1750,
    location: "Barcelona",
    country: "Spain",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Washer"],
    image: { url: img("photo-1554995207-c18c203602cb"), filename: "barcelona" },
    coordinates: { lat: 41.3851, lng: 2.1734 },
  },
  {
    title: "Scottish Highland Castle Wing",
    description: "Four-poster beds, tapestries, and whisky tastings in the great hall.",
    category: "Castles",
    propertyType: "Unique stay",
    price: 4500,
    location: "Scottish Highlands",
    country: "United Kingdom",
    maxGuests: 6,
    amenities: ["WiFi", "Breakfast", "Free parking"],
    image: { url: img("photo-1585543805890-6051f7829f98"), filename: "castle" },
    coordinates: { lat: 57.4778, lng: -4.2026 },
  },
  {
    title: "Rajasthan Heritage Haveli",
    description: "Courtyard fountain, hand-painted walls, and rooftop dining.",
    category: "Castles",
    propertyType: "Unique stay",
    price: 3200,
    location: "Jaipur",
    country: "India",
    maxGuests: 8,
    amenities: ["WiFi", "Breakfast", "Pool", "Air conditioning"],
    image: { url: img("photo-1566073771259-6a8506099945"), filename: "haveli" },
    coordinates: { lat: 26.9124, lng: 75.7873 },
  },
  {
    title: "Lakeside Treehouse Camp",
    description: "Elevated deck among pines with kayak launch and fire pit.",
    category: "Camping",
    propertyType: "Unique stay",
    price: 890,
    location: "Lake Tahoe",
    country: "United States",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Pet friendly"],
    image: { url: img("photo-1520250497591-112f2f40a3f4"), filename: "treehouse" },
    coordinates: { lat: 39.0968, lng: -120.0324 },
  },
  {
    title: "Desert Glamping Suite",
    description: "Canvas luxury tents with AC, en-suite bath, and dune dinners.",
    category: "Camping",
    propertyType: "Unique stay",
    price: 1100,
    location: "Jaisalmer",
    country: "India",
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Air conditioning"],
    image: { url: img("photo-1478131143081-825fadf4e390"), filename: "glamping" },
    coordinates: { lat: 26.9157, lng: 70.9083 },
  },
  {
    title: "Tuscany Vineyard Farmhouse",
    description: "Olive groves, wine tastings, and farmhouse kitchen with brick oven.",
    category: "Farm",
    propertyType: "Entire place",
    price: 1650,
    location: "Florence",
    country: "Italy",
    maxGuests: 6,
    amenities: ["WiFi", "Kitchen", "Free parking", "Pet friendly"],
    image: { url: img("photo-1566024244535-050f6aef2f4e"), filename: "farm" },
    coordinates: { lat: 43.7696, lng: 11.2558 },
  },
  {
    title: "Countryside Barn Conversion",
    description: "Exposed beams, meadow views, and fresh eggs from the coop.",
    category: "Farm",
    propertyType: "Entire place",
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    maxGuests: 5,
    amenities: ["WiFi", "Kitchen", "Free parking", "Pet friendly"],
    image: { url: img("photo-1416331108676-22c7610c9f9e"), filename: "barn" },
    coordinates: { lat: 51.8333, lng: -1.8333 },
  },
  {
    title: "Arctic Glass Igloo Suite",
    description: "Northern lights from your bed, heated floors, and sauna access.",
    category: "Arctic",
    propertyType: "Unique stay",
    price: 3900,
    location: "Rovaniemi",
    country: "Finland",
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Air conditioning"],
    image: { url: img("photo-1531366936337-7c912a33869b"), filename: "arctic" },
    coordinates: { lat: 66.5039, lng: 25.7294 },
  },
  {
    title: "Norwegian Fjord Cabin",
    description: "Floor heating, panoramic fjord windows, and snowmobile trails.",
    category: "Arctic",
    propertyType: "Entire place",
    price: 2400,
    location: "Bergen",
    country: "Norway",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Washer"],
    image: { url: img("photo-1483921020237-2ff51e8a4d6"), filename: "fjord" },
    coordinates: { lat: 60.3913, lng: 5.3221 },
  },
  {
    title: "Boutique City Hotel Room",
    description: "Rooftop bar, concierge, and premium linens in the design district.",
    category: "Rooms",
    propertyType: "Hotel",
    price: 1450,
    location: "Miami",
    country: "United States",
    maxGuests: 2,
    amenities: ["WiFi", "Pool", "Air conditioning", "TV", "Breakfast"],
    image: { url: img("photo-1560067174-8943bd0b3c40"), filename: "hotel" },
    coordinates: { lat: 25.7617, lng: -80.1918 },
  },
  {
    title: "Heritage Boutique Suite",
    description: "High ceilings, clawfoot tub, and afternoon tea service.",
    category: "Rooms",
    propertyType: "Hotel",
    price: 1680,
    location: "Charleston",
    country: "United States",
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Air conditioning", "TV"],
    image: { url: img("photo-1549187774-b4e9b0445b41"), filename: "boutique" },
    coordinates: { lat: 32.7765, lng: -79.9311 },
  },
  {
    title: "Designer Private Room",
    description: "En-suite bath, shared chef's kitchen, and garden terrace.",
    category: "Rooms",
    propertyType: "Private room",
    price: 780,
    location: "Amsterdam",
    country: "Netherlands",
    maxGuests: 2,
    amenities: ["WiFi", "Kitchen", "Washer"],
    image: { url: img("photo-1631049307264-da0ec9d70304"), filename: "room" },
    coordinates: { lat: 52.3676, lng: 4.9041 },
  },
  {
    title: "Safari Lodge Tent",
    description: "Game drives included, plunge pool, and gourmet bush dinners.",
    category: "Trending",
    propertyType: "Unique stay",
    price: 4800,
    location: "Serengeti",
    country: "Tanzania",
    maxGuests: 4,
    amenities: ["WiFi", "Breakfast", "Pool"],
    image: { url: img("photo-1516423897281-444d8d46f531"), filename: "safari" },
    coordinates: { lat: -2.3333, lng: 34.8333 },
  },
  {
    title: "Desert Luxury Oasis",
    description: "Private dunes, camel rides, and infinity pool under the stars.",
    category: "Trending",
    propertyType: "Entire place",
    price: 5600,
    location: "Dubai",
    country: "United Arab Emirates",
    maxGuests: 6,
    amenities: ["WiFi", "Pool", "Air conditioning", "Breakfast"],
    image: { url: img("photo-1518684079-3c830dcef090"), filename: "dubai" },
    coordinates: { lat: 25.2048, lng: 55.2708 },
  },
  {
    title: "Rainforest Eco Lodge",
    description: "Canopy walkways, wildlife tours, and farm-to-table dining.",
    category: "Trending",
    propertyType: "Unique stay",
    price: 1350,
    location: "Costa Rica",
    country: "Costa Rica",
    maxGuests: 4,
    amenities: ["WiFi", "Breakfast", "Pet friendly"],
    image: { url: img("photo-1520250497591-112f2f40a3f4"), filename: "rainforest" },
    coordinates: { lat: 9.7489, lng: -84.0907 },
  },
  {
    title: "Penthouse Sky Suite",
    description: "Wraparound terrace, private elevator, and chef on request.",
    category: "Trending",
    propertyType: "Entire place",
    price: 7200,
    location: "Los Angeles",
    country: "United States",
    maxGuests: 6,
    amenities: ["WiFi", "Pool", "Kitchen", "Workspace", "TV"],
    image: { url: img("photo-1600596542815-ffad4c1539a9"), filename: "penthouse" },
    coordinates: { lat: 34.0522, lng: -118.2437 },
  },
  {
    title: "Canal House Amsterdam",
    description: "Historic beams, boat dock, and bikes included for exploring.",
    category: "Iconic Cities",
    propertyType: "Entire place",
    price: 1980,
    location: "Amsterdam",
    country: "Netherlands",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Washer"],
    image: { url: img("photo-1534351590666-13e3e96b5017"), filename: "canal" },
    coordinates: { lat: 52.3676, lng: 4.9041 },
  },
  {
    title: "Swiss Alpine Chalet",
    description: "Cable car nearby, fondue nights, and snow-covered balconies.",
    category: "Mountains",
    propertyType: "Entire place",
    price: 3100,
    location: "Verbier",
    country: "Switzerland",
    maxGuests: 7,
    amenities: ["WiFi", "Kitchen", "Free parking", "Washer"],
    image: { url: img("photo-1502784444187-359ac186c5bb"), filename: "swiss" },
    coordinates: { lat: 46.0968, lng: 7.2285 },
  },
  {
    title: "Greek Cliffside Villa",
    description: "Whitewashed walls, blue domes, and sunset infinity pool.",
    category: "Amazing pools",
    propertyType: "Entire place",
    price: 3800,
    location: "Santorini",
    country: "Greece",
    maxGuests: 5,
    amenities: ["WiFi", "Pool", "Kitchen", "Air conditioning"],
    image: { url: img("photo-1613490493576-2c3796f14706"), filename: "santorini" },
    coordinates: { lat: 36.3932, lng: 25.4615 },
  },
  {
    title: "Kerala Backwater Houseboat",
    description: "Floating suite with chef, ayurvedic spa, and palm-lined canals.",
    category: "Trending",
    propertyType: "Unique stay",
    price: 1250,
    location: "Alleppey",
    country: "India",
    maxGuests: 4,
    amenities: ["WiFi", "Breakfast", "Air conditioning"],
    image: { url: img("photo-1602216051446-39ca40e0a037"), filename: "houseboat" },
    coordinates: { lat: 9.4981, lng: 76.3388 },
  },
  {
    title: "Moroccan Riad Suite",
    description: "Zellige tiles, central courtyard fountain, and rooftop mint tea.",
    category: "Iconic Cities",
    propertyType: "Private room",
    price: 920,
    location: "Marrakech",
    country: "Morocco",
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Air conditioning"],
    image: { url: img("photo-1569163139394-de4798aa62ea"), filename: "riad" },
    coordinates: { lat: 31.6295, lng: -7.9811 },
  },
  {
    title: "Seoul Hanok Stay",
    description: "Traditional heated floors, tea ceremony, and Bukchon village walks.",
    category: "Iconic Cities",
    propertyType: "Unique stay",
    price: 1100,
    location: "Seoul",
    country: "South Korea",
    maxGuests: 3,
    amenities: ["WiFi", "Kitchen", "Air conditioning"],
    image: { url: img("photo-1583417319070-4a69db38a48d"), filename: "hanok" },
    coordinates: { lat: 37.5665, lng: 126.978 },
  },
  {
    title: "Patagonia Eco Dome",
    description: "Geodesic dome with glacier views and stargazing deck.",
    category: "Camping",
    propertyType: "Unique stay",
    price: 1580,
    location: "Patagonia",
    country: "Chile",
    maxGuests: 2,
    amenities: ["WiFi", "Kitchen", "Pet friendly"],
    image: { url: img("photo-1506905925346-21bda4d32df4"), filename: "dome" },
    coordinates: { lat: -50.9423, lng: -73.4068 },
  },
  {
    title: "Vineyard Pool Estate",
    description: "Winery tours, chef's table, and heated pool among vines.",
    category: "Amazing pools",
    propertyType: "Entire place",
    price: 4100,
    location: "Napa Valley",
    country: "United States",
    maxGuests: 10,
    amenities: ["WiFi", "Pool", "Kitchen", "Free parking"],
    image: { url: img("photo-1600596542815-ffad4c1539a9"), filename: "vineyard" },
    coordinates: { lat: 38.5025, lng: -122.2654 },
  },
  {
    title: "Singapore Marina Suite",
    description: "Bay views, infinity pool access, and smart-home controls.",
    category: "Rooms",
    propertyType: "Hotel",
    price: 2650,
    location: "Singapore",
    country: "Singapore",
    maxGuests: 3,
    amenities: ["WiFi", "Pool", "Workspace", "Air conditioning", "TV"],
    image: { url: img("photo-1525625293386-3f8f99389edd"), filename: "singapore" },
    coordinates: { lat: 1.3521, lng: 103.8198 },
  },
  {
    title: "Sydney Harbour Apartment",
    description: "Opera House glimpses, harbour ferry stop, and modern kitchen.",
    category: "Iconic Cities",
    propertyType: "Entire place",
    price: 2350,
    location: "Sydney",
    country: "Australia",
    maxGuests: 4,
    amenities: ["WiFi", "Kitchen", "Washer", "Workspace"],
    image: { url: img("photo-1506973035872-a4ec16b8e8d9"), filename: "sydney" },
    coordinates: { lat: -33.8688, lng: 151.2093 },
  },
];

const CURATED_LISTING_CATALOG = LISTING_CATALOG.map((listing) => {
  const image = TITLE_IMAGE_MAP[listing.title] || listing.image;
  return {
    ...listing,
    image: { ...image },
    images: [{ ...image }],
  };
});

module.exports = { LISTING_CATALOG: CURATED_LISTING_CATALOG };
